/**
 * The MediaMTX config PPM generates for each run, and the one place the relay's exposure is
 * decided.
 *
 * The archive ships its own `mediamtx.yml` that listens on every interface and turns on RTSP,
 * RTMP, HLS, SRT, MoQ, an HTTP API, metrics and pprof. None of that is wanted, and MoQ in
 * particular writes a self-signed `auto.crt`/`auto.key` beside itself on first start. PPM
 * writes this file instead and passes it explicitly, so the shipped one is never read.
 *
 * Verified against v1.21.1: the generated config leaves exactly three sockets open —
 *   127.0.0.1:<rtsp>  TCP   ffmpeg pushes the H.264 it already encoded
 *   127.0.0.1:<whep>  TCP   WHEP signalling, reached only through PPM's authenticated proxy
 *   *:<ice>           UDP   the media itself
 *
 * The UDP port is the one thing that cannot be confined to loopback: WebRTC media goes
 * peer-to-peer, so a browser on the LAN or the tailnet has to be able to reach it. What
 * protects it is the ICE credentials — a random ufrag/password minted per session and carried
 * in the SDP, which only travels through the authenticated proxy. That is the standard WebRTC
 * model, but it does mean the port answers to anyone who can reach it *and* already holds a
 * session's SDP, so the path name is random per session too rather than a guessable "desktop".
 */
import { randomBytes } from "node:crypto";

export interface MediamtxConfigOptions {
  /** Loopback TCP port ffmpeg pushes RTSP to. */
  rtspPort: number;
  /** Loopback TCP port serving WHEP; PPM proxies to it. */
  whepPort: number;
  /** UDP port ICE media flows over. Bound on every interface by necessity. */
  iceUdpPort: number;
  /** Stream path, from `randomStreamPath()`. */
  pathName: string;
}

/**
 * An unguessable path per session. MediaMTX path names allow only word characters, so this is
 * hex rather than base64url.
 */
export function randomStreamPath(): string {
  return `s${randomBytes(16).toString("hex")}`;
}

/** Where ffmpeg pushes, and where the relay reads from. */
export function rtspPublishUrl(rtspPort: number, pathName: string): string {
  return `rtsp://127.0.0.1:${rtspPort}/${pathName}`;
}

/** The WHEP endpoint on the relay, which PPM proxies rather than exposes. */
export function whepUrl(whepPort: number, pathName: string): string {
  return `http://127.0.0.1:${whepPort}/${pathName}/whep`;
}

/**
 * MediaMTX rejects unknown config keys outright (`json: unknown field "..."`), which is why
 * every switch here is spelled out rather than trusted to default: a key that a future release
 * renames fails loudly at start instead of silently leaving a listener open.
 */
export function buildMediamtxConfig(opts: MediamtxConfigOptions): string {
  const { rtspPort, whepPort, iceUdpPort, pathName } = opts;
  return [
    "# Generated by PPM for one Remote Desktop session. Edits are overwritten on every start.",
    "logLevel: warn",
    "",
    "# RTSP ingest: loopback only, TCP only. ffmpeg is the only thing that ever publishes.",
    "rtsp: yes",
    "rtspTransports: [tcp]",
    `rtspAddress: 127.0.0.1:${rtspPort}`,
    "",
    "# WebRTC out. The signalling port stays on loopback and is reached through PPM's",
    "# authenticated proxy; only the ICE/UDP port faces the network.",
    "webrtc: yes",
    `webrtcAddress: 127.0.0.1:${whepPort}`,
    `webrtcLocalUDPAddress: :${iceUdpPort}`,
    "webrtcIPsFromInterfaces: yes",
    "",
    "# Everything else off. MoQ also writes auto.crt/auto.key beside itself when left on.",
    "rtmp: no",
    "hls: no",
    "srt: no",
    "moq: no",
    "api: no",
    "metrics: no",
    "pprof: no",
    "playback: no",
    "",
    "paths:",
    `  ${pathName}:`,
    "    source: publisher",
    "",
  ].join("\n");
}
