/**
 * What the Structure tab shows of a table, in DBGate's sections and columns, and what its column
 * menu copies. Pure, so the rules — which indexes have a section of their own, how a definition
 * is spelled — are tested without a browser.
 */
import type { DbForeignKey, DbStructureColumn, DbTableStructure } from "../../../../shared/db-structure";
import type { DialectName } from "../../../../shared/db-types";
import { quoteIdentifier } from "../../../../shared/sql-identifiers";

export interface StructureColumnRow {
  /** 1-based, DBGate's `#`. */
  ordinal: number;
  name: string;
  /** In the primary key, else in a foreign key, else neither: the icon beside the name. */
  role: "pk" | "fk" | null;
  notNull: boolean;
  type: string;
  defaultValue: string;
  computedExpression: string;
  comment: string;
}

export function columnRows(s: DbTableStructure): StructureColumnRow[] {
  const pk = new Set(s.primaryKey?.columns ?? []);
  const fk = new Set(s.foreignKeys.flatMap((k) => k.columns));
  return s.columns.map((c, i) => ({
    ordinal: i + 1,
    name: c.name,
    role: pk.has(c.name) ? "pk" : fk.has(c.name) ? "fk" : null,
    notNull: !c.nullable,
    type: c.type,
    defaultValue: c.defaultValue ?? "",
    computedExpression: c.computedExpression ?? "",
    comment: c.comment ?? "",
  }));
}

/** The indexes with no section of their own elsewhere (shared with the table editor's model). */
export { ownIndexes } from "../../../../shared/db-table-model";

export interface ForeignKeyRow {
  name: string | null;
  baseColumns: string;
  /** Schema-qualified only when it is not the table's own schema. */
  refTable: string;
  refColumns: string;
  onUpdate: string;
  onDelete: string;
  /** The table holding the key — for a dependency, the one pointing here. */
  holder: string;
}

const qualified = (schema: string | null, table: string, own: string | null) => (schema && schema !== own ? `${schema}.${table}` : table);

export function foreignKeyRow(fk: DbForeignKey, ownSchema: string | null): ForeignKeyRow {
  return {
    name: fk.name,
    baseColumns: fk.columns.join(", "),
    refTable: qualified(fk.refSchema, fk.refTable, ownSchema),
    refColumns: fk.refColumns.join(", "),
    onUpdate: fk.onUpdate,
    onDelete: fk.onDelete,
    holder: qualified(fk.schema, fk.table, ownSchema),
  };
}

/** "Copy names": the names as a SELECT list takes them. */
export function columnNames(names: readonly string[]): string {
  return names.join(", ");
}

/** "Copy definitions": each column as CREATE TABLE spells it, one per line. */
export function columnDefinitions(columns: readonly DbStructureColumn[], dialect: DialectName): string {
  return columns.map((c) => columnDefinition(c, dialect)).join(",\n");
}

export function columnDefinition(c: DbStructureColumn, dialect: DialectName): string {
  const parts = [quoteIdentifier(c.name, dialect), c.type];
  if (c.generated && c.computedExpression) {
    // Postgres before 18 has stored generated columns only; MySQL and SQLite default to virtual.
    parts.push(`GENERATED ALWAYS AS (${c.computedExpression})${dialect === "postgres" ? " STORED" : ""}`);
  }
  if (!c.nullable) parts.push("NOT NULL");
  if (c.defaultValue !== null && !c.generated) parts.push(`DEFAULT ${c.defaultValue}`);
  // A serial's nextval() default already says it; an identity column has no default to say it with.
  // Whether it was ALWAYS is not in the structure, and BY DEFAULT accepts every insert ALWAYS does.
  if (c.autoIncrement && dialect === "mysql") parts.push("AUTO_INCREMENT");
  if (c.autoIncrement && dialect === "postgres" && c.defaultValue === null) parts.push("GENERATED BY DEFAULT AS IDENTITY");
  return parts.join(" ");
}
