/**
 * Bundled CLI reference fallback for compiled binary (when generator script is unavailable).
 * Auto-generated by: bun scripts/generate-bot-coordinator.ts --update-default
 *
 * To regenerate: bun generate:bot
 */

// prettier-ignore
export const DEFAULT_CLI_REFERENCE = `# PPM CLI Reference
## Core Commands (Server & system management)
\`\`\`
ppm start
  Start the PPM server (background by default)
  -p, --port <port> — Port to listen on
  -s, --share — (deprecated) Tunnel is now always enabled
  --profile <name> — DB profile name (e.g. 'dev' → ppm.dev.db)

ppm stop
  Stop the PPM server (supervisor stays alive)
  -a, --all — Kill all PPM and cloudflared processes (including untracked)
  --kill — Full shutdown (kills supervisor too)

ppm down
  Fully shut down PPM (supervisor + server + tunnel)

ppm restart
  Restart the server (keeps tunnel alive)
  --force — Force resume from paused state

ppm status
  Show PPM daemon status
  -a, --all — Show all PPM and cloudflared processes (including untracked)
  --json — Output as JSON

ppm open
  Open PPM in browser

ppm logs
  View PPM daemon logs
  -n, --tail <lines> — Number of lines to show [default: 50]
  -f, --follow — Follow log output
  --clear — Clear log file

ppm report
  Report a bug on GitHub (pre-fills env info + logs)

ppm init
  Initialize PPM configuration (interactive or via flags)
  -p, --port <port> — Port to listen on
  --scan <path> — Directory to scan for git repos
  --auth — Enable authentication
  --no-auth — Disable authentication
  --password <pw> — Set access password
  --share — Pre-install cloudflared for sharing
  -y, --yes — Non-interactive mode (use defaults + flags)

ppm upgrade
  Check for and install PPM updates
\`\`\`
## ppm projects — Manage registered projects
\`\`\`
ppm projects list
  List all registered projects

ppm projects add <path>
  Add a project to the registry
  -n, --name <name> — Project name (defaults to folder name)

ppm projects remove <name>
  Remove a project from the registry
\`\`\`
## ppm config — Configuration management
\`\`\`
ppm config get <key>
  Get a config value (e.g. port, auth.enabled)

ppm config set <key> <value>
  Set a config value (e.g. port 9090)
\`\`\`
## ppm git — Git operations for a project
\`\`\`
ppm git status
  Show working tree status
  -p, --project <name> — Project name or path

ppm git log
  Show recent commits
  -p, --project <name> — Project name or path
  -n, --count <n> — Number of commits to show [default: 20]

ppm git diff [ref1] [ref2]
  Show diff between refs or working tree
  -p, --project <name> — Project name or path

ppm git stage <files...>
  Stage files (use "." to stage all)
  -p, --project <name> — Project name or path

ppm git unstage <files...>
  Unstage files
  -p, --project <name> — Project name or path

ppm git commit
  Commit staged changes
  -p, --project <name> — Project name or path
  -m, --message <msg> — Commit message (required)

ppm git push
  Push to remote
  -p, --project <name> — Project name or path
  --remote <remote> — Remote name [default: origin]
  --branch <branch> — Branch name

ppm git pull
  Pull from remote
  -p, --project <name> — Project name or path
  --remote <remote> — Remote name
  --branch <branch> — Branch name

ppm git branch create <name>
  Create and checkout a new branch
  -p, --project <name> — Project name or path
  --from <ref> — Base ref (commit/branch/tag)

ppm git branch checkout <name>
  Switch to a branch
  -p, --project <name> — Project name or path

ppm git branch delete <name>
  Delete a branch
  -p, --project <name> — Project name or path
  -f, --force — Force delete

ppm git branch merge <source>
  Merge a branch into current branch
  -p, --project <name> — Project name or path
\`\`\`
## ppm chat — AI chat sessions
\`\`\`
ppm chat list
  List all chat sessions
  -p, --project <name> — Filter by project name

ppm chat create
  Create a new chat session
  -p, --project <name> — Project name or path
  --provider <provider> — AI provider (default: claude)

ppm chat send <session-id> <message>
  Send a message and stream response to stdout
  -p, --project <name> — Project name or path

ppm chat resume <session-id>
  Resume an interactive chat session
  -p, --project <name> — Project name or path

ppm chat delete <session-id>
  Delete a chat session
\`\`\`
## ppm db — Database connections & queries
\`\`\`
ppm db list
  List all saved database connections

ppm db add
  Add a new database connection
  -n, --name <name> — Connection name (unique) (required)
  -t, --type <type> — Database type: sqlite | postgres (required)
  -c, --connection-string <url> — PostgreSQL connection string
  -f, --file <path> — SQLite file path (absolute)
  -g, --group <group> — Group name
  --color <color> — Tab color (hex, e.g. #3b82f6)

ppm db remove <name>
  Remove a saved connection (by name or ID)

ppm db test <name>
  Test a saved connection

ppm db tables <name>
  List tables in a database connection

ppm db schema <name> <table>
  Show table schema (columns, types, constraints)
  -s, --schema <schema> — PostgreSQL schema name [default: public]

ppm db data <name> <table>
  View table data (paginated)
  -p, --page <page> — Page number [default: 1]
  -l, --limit <limit> — Rows per page [default: 50]
  --order <column> — Order by column
  --desc — Descending order
  -s, --schema <schema> — PostgreSQL schema name [default: public]

ppm db query <name> <sql>
  Execute a SQL query against a saved connection
\`\`\`
## ppm autostart — Auto-start on boot
\`\`\`
ppm autostart enable
  Register PPM to start automatically on boot
  -p, --port <port> — Override port
  -s, --share — (deprecated) Tunnel is now always enabled
  --profile <name> — DB profile name

ppm autostart disable
  Remove PPM auto-start registration

ppm autostart status
  Show auto-start status
  --json — Output as JSON
\`\`\`
## ppm cloud — PPM Cloud — device registry + tunnel
\`\`\`
ppm cloud login
  Sign in with Google
  --url <url> — Cloud URL override
  --device-code — Force device code flow (for remote terminals)

ppm cloud logout
  Sign out from PPM Cloud

ppm cloud link
  Register this machine with PPM Cloud
  -n, --name <name> — Machine display name

ppm cloud unlink
  Remove this machine from PPM Cloud

ppm cloud status
  Show PPM Cloud connection status
  --json — Output as JSON

ppm cloud devices
  List all registered devices from cloud
  --json — Output as JSON
\`\`\`
## ppm ext — Manage PPM extensions
\`\`\`
ppm ext install <name>
  Install an extension from npm

ppm ext remove <name>
  Remove an installed extension

ppm ext list
  List installed extensions

ppm ext enable <name>
  Enable an extension

ppm ext disable <name>
  Disable an extension

ppm ext dev <path>
  Symlink a local extension for development
\`\`\`
## ppm bot — PPMBot coordinator utilities
\`\`\`
ppm bot delegate
  Delegate a task to a project subagent
  --chat <id> — Telegram chat ID (required)
  --project <name> — Project name (required)
  --prompt <text> — Enriched task prompt (required)
  --timeout <ms> — Timeout in milliseconds [default: 900000]

ppm bot task-status <id>
  Get status of a delegated task

ppm bot task-result <id>
  Get full result of a completed task

ppm bot tasks
  List recent delegated tasks
  --chat <id> — Telegram chat ID (auto-detected if single)

ppm bot memory save <content>
  Save a cross-project memory
  -c, --category <cat> — Category: fact|preference|decision|architecture|issue [default: fact]
  -s, --session <id> — Session ID (optional)

ppm bot memory list
  List active cross-project memories
  -l, --limit <n> — Max results [default: 30]
  --json — Output as JSON

ppm bot memory forget <topic>
  Delete memories matching a topic (FTS5 search)

ppm bot project list
  List available projects
  --json — Output as JSON

ppm bot status
  Show current status and running tasks
  --chat <id> — Telegram chat ID (auto-detected if single)
  --json — Output as JSON

ppm bot version
  Show PPM version

ppm bot restart
  Restart the PPM server

ppm bot help
  Show all bot CLI commands
\`\`\`

## Quick Reference — Task Delegation
\`\`\`
ppm bot delegate --chat <chatId> --project <name> --prompt "<enriched task>"
ppm bot task-status <id>
ppm bot task-result <id>
ppm bot tasks
\`\`\`

## Quick Reference — Memory
\`\`\`
ppm bot memory save "<content>" -c <category>
ppm bot memory list
ppm bot memory forget "<topic>"
\`\`\`

## Tips
- Use \`--json\` flag when parsing command output programmatically
- For git/chat/db operations: always specify \`--project <name>\` or connection name
`;
