/**
 * The SQL tab's CREATE scripts against real servers: every object's script, run through PPM's own
 * Query route on an empty database, must build the same object again — which is checked by
 * asking the copy for its scripts and structure and finding them equal to the original's.
 * Runs only when the URLs name disposable servers, e.g.
 *
 *   docker run --rm -d -p 127.0.0.1:25432:5432 -e POSTGRES_PASSWORD=x postgres:17
 *   docker run --rm -d -p 127.0.0.1:23306:3306 -e MYSQL_ROOT_PASSWORD=x mysql:8.4
 *   docker run --rm -d -p 127.0.0.1:23307:3306 -e MARIADB_ROOT_PASSWORD=x mariadb:11
 *   PPM_TEST_PG_URL=postgres://postgres:x@127.0.0.1:25432/postgres \
 *   PPM_TEST_MYSQL_URL=mysql://root:x@127.0.0.1:23306 PPM_TEST_MARIADB_URL=mariadb://root:x@127.0.0.1:23307 \
 *     bun test tests/integration/database-object-sql.test.ts
 *
 * Each run creates its databases under names of its own and drops them at the end.
 */
import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import { Hono } from "hono";
import postgres from "postgres";
import mysql2 from "mysql2/promise";
import { openTestDb, setDb } from "../../src/services/db.service.ts";
import { initAdapters } from "../../src/services/database/init-adapters.ts";
import { installDbDriver } from "../../src/services/database/drivers/db-driver-install.ts";
import { postgresService } from "../../src/services/postgres.service.ts";
import { mysqlService } from "../../src/services/mysql.service.ts";
import { databaseRoutes } from "../../src/server/routes/database.ts";
import type { QueryRunResponse } from "../../src/shared/db-grid.ts";
import type { DbObject, DbObjectList, DbObjectScripts, DbTableStructure } from "../../src/shared/db-structure.ts";
import type { DbType } from "../../src/shared/db-types.ts";
import { copyingRunner } from "../helpers/db-driver-offline-install.ts";

const RUN = `${Date.now().toString(36)}${Math.floor(Math.random() * 1e6).toString(36)}`;
const PG_URL = process.env.PPM_TEST_PG_URL;

const app = () => new Hono().route("/db", databaseRoutes);

async function call<T>(method: string, path: string, body?: unknown): Promise<{ status: number; data: T; error?: string }> {
  const res = await app().request(path, {
    method,
    headers: { "Content-Type": "application/json", "x-ppm-client": "web" },
    ...(body === undefined ? {} : { body: JSON.stringify(body) }),
  });
  const json = (await res.json()) as { data: T; error?: string };
  return { status: res.status, data: json.data, error: json.error };
}

async function createConnection(type: DbType, name: string, connectionString: string): Promise<number> {
  const res = await call<{ id: number }>("POST", "/db/connections", { type, name, connectionConfig: { type, connectionString } });
  await call("PUT", `/db/connections/${res.data.id}`, { readonly: 0 });
  return res.data.id;
}

function scriptsUrl(id: number, o: DbObject): string {
  const qs = new URLSearchParams({ kind: o.kind, name: o.name });
  if (o.schema) qs.set("schema", o.schema);
  if (o.args !== undefined) qs.set("args", o.args);
  if (o.table) qs.set("table", o.table);
  return `/db/connections/${id}/object-sql?${qs}`;
}

async function scriptsOf(id: number, o: DbObject): Promise<DbObjectScripts> {
  const res = await call<DbObjectScripts>("GET", scriptsUrl(id, o));
  if (res.status !== 200) throw new Error(`${o.kind} ${o.name}: ${res.status} ${res.error}`);
  return res.data;
}

async function runOn(id: number, sql: string): Promise<void> {
  const res = await call<QueryRunResponse>("POST", `/db/connections/${id}/query`, { sql });
  if (res.status !== 200) throw new Error(`${res.error}\n--- while running ---\n${sql}`);
}

beforeAll(async () => {
  initAdapters();
  setDb(openTestDb());
  if (process.env.PPM_TEST_MYSQL_URL || process.env.PPM_TEST_MARIADB_URL) await installDbDriver("mysql", { run: copyingRunner("mysql") });
});

afterAll(async () => {
  await postgresService.closeAll();
  await mysqlService.closeAll();
});

describe.skipIf(!PG_URL)("CREATE scripts on Postgres", () => {
  const S = `ppm_os_${RUN}`;
  const TARGET = `ppm_os_target_${RUN}`;
  const targetUrl = (() => {
    if (!PG_URL) return "";
    const u = new URL(PG_URL);
    u.pathname = `/${TARGET}`;
    return u.toString();
  })();
  const admin = PG_URL ? postgres(PG_URL, { max: 1, onnotice: () => {} }) : null;
  let source = 0;
  let target = 0;
  let objects: DbObject[] = [];

  beforeAll(async () => {
    await admin!.unsafe(`
      CREATE SCHEMA ${S};
      CREATE TABLE ${S}.orgs (
        id serial PRIMARY KEY, name text NOT NULL UNIQUE, region text DEFAULT 'eu', created timestamptz NOT NULL DEFAULT now()
      );
      CREATE TABLE ${S}.users (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        org_id integer REFERENCES ${S}.orgs (id) ON DELETE SET NULL ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED,
        email text NOT NULL,
        price numeric(10,2), qty integer,
        total numeric GENERATED ALWAYS AS (price * qty) STORED,
        CONSTRAINT email_shape CHECK (email LIKE '%@%')
      ) WITH (fillfactor = 80);
      CREATE INDEX users_email_lower ON ${S}.users (lower(email));
      CREATE UNIQUE INDEX users_org_email ON ${S}.users (org_id, email) WHERE org_id IS NOT NULL;
      COMMENT ON TABLE ${S}.users IS 'People who log in';
      COMMENT ON COLUMN ${S}.users.email IS 'it''s a back\\slash';
      CREATE UNLOGGED TABLE ${S}.scratch (k text PRIMARY KEY, v jsonb);
      CREATE TABLE ${S}.events (id int NOT NULL, at date NOT NULL, note text, PRIMARY KEY (id, at)) PARTITION BY RANGE (at);
      CREATE TABLE ${S}.events_2026 PARTITION OF ${S}.events FOR VALUES FROM ('2026-01-01') TO ('2027-01-01');
      CREATE INDEX events_note ON ${S}.events (note);
      CREATE SEQUENCE ${S}.invoice_no AS integer START WITH 100 INCREMENT BY 5 MINVALUE 10 MAXVALUE 100000 CACHE 2 CYCLE;
      CREATE VIEW ${S}.big_users WITH (security_barrier) AS SELECT id, total FROM ${S}.users WHERE total > 100;
      COMMENT ON VIEW ${S}.big_users IS 'Over a hundred';
      CREATE MATERIALIZED VIEW ${S}.org_counts AS SELECT org_id, count(*) AS n FROM ${S}.users GROUP BY org_id;
      CREATE INDEX org_counts_org ON ${S}.org_counts (org_id);
      CREATE FUNCTION ${S}.add_one(a integer) RETURNS integer LANGUAGE sql IMMUTABLE AS 'SELECT a + 1';
      CREATE FUNCTION ${S}.add_one(a text) RETURNS text LANGUAGE sql AS $$ SELECT a || '1' $$;
      COMMENT ON FUNCTION ${S}.add_one(text) IS 'text overload';
      CREATE PROCEDURE ${S}.touch_org(p integer) LANGUAGE plpgsql AS $body$
        BEGIN
          UPDATE ${S}.orgs SET name = name WHERE id = p;
        END;
      $body$;
      CREATE FUNCTION ${S}.stamp() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          NEW.email := lower(NEW.email);
          RETURN NEW;
        END;
      $$;
      CREATE TRIGGER users_stamp BEFORE INSERT OR UPDATE OF email ON ${S}.users FOR EACH ROW EXECUTE FUNCTION ${S}.stamp();
    `);
    await admin!.unsafe(`CREATE DATABASE ${TARGET}`);
    const other = postgres(targetUrl, { max: 1, onnotice: () => {} });
    await other.unsafe(`CREATE SCHEMA ${S}`);
    await other.end();
    source = await createConnection("postgres", "os-pg-source", PG_URL!);
    target = await createConnection("postgres", "os-pg-target", targetUrl);
    objects = (await call<DbObjectList>("GET", `/db/connections/${source}/objects`)).data.objects.filter((o) => o.schema === S);
  });

  afterAll(async () => {
    await postgresService.closeAll();
    await admin!.unsafe(`DROP SCHEMA IF EXISTS ${S} CASCADE`);
    await admin!.unsafe(`DROP DATABASE IF EXISTS ${TARGET} WITH (FORCE)`);
    await admin!.end();
  });

  it("writes a table the way it was declared, keys and all", async () => {
    const users = await scriptsOf(source, objects.find((o) => o.name === "users")!);
    expect(users.create).toBe([
      `CREATE TABLE "${S}"."users" (`,
      `  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,`,
      `  "org_id" integer,`,
      `  "email" text NOT NULL,`,
      `  "price" numeric(10,2),`,
      `  "qty" integer,`,
      `  "total" numeric GENERATED ALWAYS AS ((price * (qty)::numeric)) STORED,`,
      `  CONSTRAINT "users_pkey" PRIMARY KEY (id),`,
      `  CONSTRAINT "users_org_id_fkey" FOREIGN KEY (org_id) REFERENCES ${S}.orgs(id) ON UPDATE CASCADE ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,`,
      `  CONSTRAINT "email_shape" CHECK (email ~~ '%@%'::text)`,
      `)`,
      `WITH (fillfactor=80);`,
      `CREATE INDEX users_email_lower ON ${S}.users USING btree (lower(email));`,
      `CREATE UNIQUE INDEX users_org_email ON ${S}.users USING btree (org_id, email) WHERE (org_id IS NOT NULL);`,
      `COMMENT ON TABLE "${S}"."users" IS 'People who log in';`,
      `COMMENT ON COLUMN "${S}"."users"."email" IS E'it''s a back\\\\slash';`,
    ].join("\n"));
    expect(users.select).toBe(`SELECT "id", "org_id", "email", "price", "qty", "total"\nFROM "${S}"."users";`);
    expect(users.insert).toBe(`INSERT INTO "${S}"."users" ("org_id", "email", "price", "qty")\nVALUES (?, ?, ?, ?);`);

    const orgs = await scriptsOf(source, objects.find((o) => o.name === "orgs")!);
    // Its sequence does not exist where the script is run, so the default is written as serial.
    expect(orgs.create.split("\n")[1]).toBe(`  "id" serial NOT NULL,`);
  });

  it("builds every object again on an empty database, through the Query route", async () => {
    // A column's own sequence comes with its table; only a sequence of its own is created apart.
    const standalone = (o: DbObject) => o.kind !== "sequence" || o.name === "invoice_no";
    const order = ["sequence", "function", "procedure", "table", "view", "matview", "trigger"];
    const tables = ["orgs", "users", "scratch", "events", "events_2026"];
    const ordered = objects.filter(standalone).sort((a, b) =>
      order.indexOf(a.kind) - order.indexOf(b.kind) || tables.indexOf(a.name) - tables.indexOf(b.name));
    const original = new Map<string, DbObjectScripts>();
    for (const o of ordered) original.set(`${o.kind}:${o.name}:${o.args ?? ""}`, await scriptsOf(source, o));
    for (const o of ordered) await runOn(target, original.get(`${o.kind}:${o.name}:${o.args ?? ""}`)!.create);

    const copies = (await call<DbObjectList>("GET", `/db/connections/${target}/objects`)).data.objects.filter((o) => o.schema === S);
    expect(copies.map((o) => `${o.kind}:${o.name}:${o.args ?? ""}`).sort())
      .toEqual(objects.map((o) => `${o.kind}:${o.name}:${o.args ?? ""}`).sort());
    for (const o of ordered) {
      expect(await scriptsOf(target, o), `${o.kind} ${o.name}`).toEqual(original.get(`${o.kind}:${o.name}:${o.args ?? ""}`)!);
    }
    for (const o of objects.filter((x) => x.kind === "table" || x.kind === "view" || x.kind === "matview")) {
      const qs = `table=${encodeURIComponent(o.name)}&schema=${S}`;
      const a = await call<DbTableStructure>("GET", `/db/connections/${source}/structure?${qs}`);
      const b = await call<DbTableStructure>("GET", `/db/connections/${target}/structure?${qs}`);
      expect(b.data, o.name).toEqual(a.data);
    }
  });

  it("tells overloads apart by their arguments, and answers 404 for what is not there", async () => {
    const text = await call<DbObjectScripts>("GET", `/db/connections/${source}/object-sql?kind=function&name=add_one&schema=${S}&args=a%20text`);
    expect(text.data.create).toContain("RETURNS text");
    expect(text.data.create).toEndWith(`COMMENT ON FUNCTION "${S}"."add_one"(a text) IS 'text overload';`);
    const int = await call<DbObjectScripts>("GET", `/db/connections/${source}/object-sql?kind=function&name=add_one&schema=${S}&args=a%20integer`);
    expect(int.data.create).toContain("RETURNS integer");
    expect((await call("GET", `/db/connections/${source}/object-sql?kind=table&name=nope&schema=${S}`)).status).toBe(404);
    expect((await call("GET", `/db/connections/${source}/object-sql?kind=bogus&name=users&schema=${S}`)).status).toBe(400);
  });
});

for (const engine of [
  { type: "mysql" as const, url: process.env.PPM_TEST_MYSQL_URL },
  { type: "mariadb" as const, url: process.env.PPM_TEST_MARIADB_URL },
]) {
  describe.skipIf(!engine.url)(`CREATE scripts on ${engine.type}`, () => {
    const SRC = `ppm_os_src_${engine.type}_${RUN}`;
    const DST = `ppm_os_dst_${engine.type}_${RUN}`;
    const base = engine.url?.replace(/\/$/, "") ?? "";
    let admin: mysql2.Connection;
    let source = 0;
    let target = 0;
    let objects: DbObject[] = [];
    /**
     * The copy lives in another database, whose name is the only thing allowed to differ — and
     * MySQL's spelling of a column's collation: a table created from its own `SHOW CREATE TABLE`
     * prints `CHARACTER SET utf8mb4 COLLATE …` where the original printed `COLLATE …` alone
     * (measured on 8.4, with no PPM in between). The structures below compare equal regardless.
     */
    const same = <T>(value: T): T => JSON.parse(JSON.stringify(value).replaceAll(DST, SRC)) as T;
    const spelling = (scripts: DbObjectScripts): DbObjectScripts => ({ ...scripts, create: scripts.create.replace(/ CHARACTER SET \w+(?= COLLATE )/g, "") });

    beforeAll(async () => {
      admin = await mysql2.createConnection({ uri: engine.url!.replace(/^mariadb:/, "mysql:"), multipleStatements: true });
      await admin.query(`
        CREATE DATABASE ${SRC} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
        CREATE DATABASE ${DST} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
        USE ${SRC};
        CREATE TABLE orgs (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE, region VARCHAR(8) DEFAULT 'eu') COMMENT='Tenants';
        CREATE TABLE users (
          id BIGINT AUTO_INCREMENT PRIMARY KEY,
          org_id INT, email VARCHAR(120) NOT NULL COMMENT 'Login',
          price DECIMAL(10,2), qty INT,
          total DECIMAL(20,2) AS (price * qty) STORED,
          CONSTRAINT users_org FOREIGN KEY (org_id) REFERENCES orgs (id) ON DELETE SET NULL,
          CONSTRAINT email_shape CHECK (email LIKE '%@%'),
          KEY users_email (email(20))
        );
        CREATE VIEW big_users AS SELECT id, total FROM users WHERE total > 100;
        CREATE FUNCTION add_one(a INT) RETURNS INT DETERMINISTIC RETURN a + 1;
        CREATE PROCEDURE touch_org(p INT) BEGIN UPDATE orgs SET name = name WHERE id = p; SELECT p; END;
        CREATE TRIGGER users_stamp BEFORE INSERT ON users FOR EACH ROW BEGIN SET NEW.email = LOWER(NEW.email); SET NEW.qty = COALESCE(NEW.qty, 0); END;
        ${engine.type === "mariadb" ? "CREATE SEQUENCE invoice_no START WITH 100 INCREMENT BY 5;" : ""}
      `);
      source = await createConnection(engine.type, `os-${engine.type}-source`, `${base}/${SRC}`);
      target = await createConnection(engine.type, `os-${engine.type}-target`, `${base}/${DST}`);
      objects = (await call<DbObjectList>("GET", `/db/connections/${source}/objects`)).data.objects;
    });

    afterAll(async () => {
      await mysqlService.closeAll();
      await admin.query(`DROP DATABASE IF EXISTS ${SRC}; DROP DATABASE IF EXISTS ${DST};`);
      await admin.end();
    });

    it("wraps a routine or trigger whose body holds a semicolon in DELIMITER lines", async () => {
      const trigger = await scriptsOf(source, objects.find((o) => o.name === "users_stamp")!);
      expect(trigger.create).toStartWith("DELIMITER ;;\nCREATE ");
      expect(trigger.create).toEndWith("END;;\nDELIMITER ;");
      const fn = await scriptsOf(source, objects.find((o) => o.name === "add_one")!);
      expect(fn.create).not.toContain("DELIMITER");
      expect(fn.create).toEndWith(";");
    });

    it("builds every object again on an empty database, through the Query route", async () => {
      const order = ["sequence", "table", "view", "function", "procedure", "trigger"];
      const tables = ["orgs", "users"];
      const ordered = [...objects].sort((a, b) => order.indexOf(a.kind) - order.indexOf(b.kind) || tables.indexOf(a.name) - tables.indexOf(b.name));
      const original = new Map<string, DbObjectScripts>();
      for (const o of ordered) original.set(`${o.kind}:${o.name}`, await scriptsOf(source, o));
      for (const o of ordered) await runOn(target, original.get(`${o.kind}:${o.name}`)!.create);

      const copies = (await call<DbObjectList>("GET", `/db/connections/${target}/objects`)).data.objects;
      expect(copies.map((o) => `${o.kind}:${o.name}`).sort()).toEqual(objects.map((o) => `${o.kind}:${o.name}`).sort());
      for (const o of ordered) {
        const copy = await scriptsOf(target, { ...o, schema: DST });
        expect(spelling(same(copy)), `${o.kind} ${o.name}`).toEqual(spelling(original.get(`${o.kind}:${o.name}`)!));
      }
      for (const name of ["orgs", "users", "big_users"]) {
        const a = await call<DbTableStructure>("GET", `/db/connections/${source}/structure?table=${name}&schema=${SRC}`);
        const b = await call<DbTableStructure>("GET", `/db/connections/${target}/structure?table=${name}&schema=${DST}`);
        expect(same(b.data), name).toEqual(a.data);
      }
    });

    it("gives a generated column its expression in the structure", async () => {
      const s = await call<DbTableStructure>("GET", `/db/connections/${source}/structure?table=users&schema=${SRC}`);
      const total = s.data.columns.find((c) => c.name === "total")!;
      expect(total.generated).toBe(true);
      expect(total.computedExpression?.replace(/[`()\s]/g, "")).toBe("price*qty");
      expect(s.data.columns.find((c) => c.name === "qty")!.computedExpression).toBeNull();
    });
  });
}
