/**
 * The grid against a real Postgres. Runs only when `PPM_TEST_PG_URL` names a
 * disposable database, e.g.
 *
 *   docker run --rm -d -p 25432:5432 -e POSTGRES_PASSWORD=x postgres:17
 *   PPM_TEST_PG_URL=postgres://postgres:x@127.0.0.1:25432/postgres bun test tests/integration/database-grid-postgres.test.ts
 *
 * Everything it creates lives in schemas named after this run and is dropped at the end.
 */
import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import { Hono } from "hono";
import postgres from "postgres";
import { openTestDb, setDb } from "../../src/services/db.service.ts";
import { initAdapters } from "../../src/services/database/init-adapters.ts";
import { getAdapter } from "../../src/services/database/adapter-registry.ts";
import { parseGridRequest } from "../../src/services/database/grid-query-builder.ts";
import { countGridRows, fetchGridPage, type GridTarget } from "../../src/services/database/grid.service.ts";
import { postgresService } from "../../src/services/postgres.service.ts";
import { databaseRoutes } from "../../src/server/routes/database.ts";
import type { GridCountResponse, GridResponse, QueryRunResponse } from "../../src/shared/db-grid.ts";

const PG_URL = process.env.PPM_TEST_PG_URL;
const RUN = `${Date.now().toString(36)}${Math.floor(Math.random() * 1e6).toString(36)}`;
const A = `ppm_grid_a_${RUN}`;
const B = `ppm_grid_b_${RUN}`;
const PUBLIC_TABLE = `ppm_grid_${RUN}`;

// bun test runs in UTC, where a driver that shifts timestamps by the local zone
// looks correct. A zone east of UTC makes that shift visible.
const originalTz = process.env.TZ;

const app = () => new Hono().route("/db", databaseRoutes);
let connId = 0;

async function post<T>(path: string, body: unknown): Promise<{ status: number; data: T; error?: string }> {
  const res = await app().request(path, {
    method: "POST",
    headers: { "Content-Type": "application/json", "x-ppm-client": "web" },
    body: JSON.stringify(body),
  });
  const json = (await res.json()) as { data: T; error?: string };
  return { status: res.status, data: json.data, error: json.error };
}
const grid = (body: unknown) => post<GridResponse>(`/db/connections/${connId}/grid`, body);

describe.skipIf(!PG_URL)("grid on Postgres", () => {
  const admin = PG_URL ? postgres(PG_URL, { max: 1, onnotice: () => {} }) : null;

  beforeAll(async () => {
    process.env.TZ = "Asia/Ho_Chi_Minh";
    initAdapters();
    setDb(openTestDb());
    await admin!.unsafe(`
      CREATE SCHEMA ${A};
      CREATE SCHEMA ${B};
      CREATE TABLE ${A}.users (
        id int8 PRIMARY KEY, email text, ts timestamp, tstz timestamptz, d date,
        n numeric, j jsonb, b bytea, u uuid, active boolean, tags int[]
      );
      INSERT INTO ${A}.users VALUES (
        9007199254740993, 'Alice@Example.com', '2024-01-01 10:00:00', '2024-01-01 03:00:00+00', '2024-01-01',
        12345678901234567890.1234567891, '{"k": 1}', '\\x0102', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', true, '{1,2}'
      );
      CREATE TABLE ${B}.users (id int, name text);
      INSERT INTO ${B}.users VALUES (1, 'b-one');
      CREATE TABLE public.${PUBLIC_TABLE} (id int, name text);
      INSERT INTO public.${PUBLIC_TABLE} VALUES (1, 'in public');
      -- In the select list, not FROM: a set-returning function in FROM is computed in
      -- full before LIMIT applies, which would make every page as slow as a count.
      CREATE VIEW ${A}.slow AS SELECT generate_series(1, 500000000) AS n;
      ANALYZE ${A}.users;
      CREATE TABLE ${A}.numbered (
        id integer PRIMARY KEY, serial_no serial, always_no bigint GENERATED ALWAYS AS IDENTITY,
        default_no int GENERATED BY DEFAULT AS IDENTITY, plain_no int DEFAULT 7
      );
    `);
    const res = await app().request("/db/connections", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ type: "postgres", name: "grid-pg", connectionConfig: { type: "postgres", connectionString: PG_URL } }),
    });
    connId = ((await res.json()) as { data: { id: number } }).data.id;
    await app().request(`/db/connections/${connId}`, {
      method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ readonly: 0 }),
    });
  });

  afterAll(async () => {
    // Assigned back, never deleted: once TZ is deleted, Bun ignores every later
    // assignment and the rest of the run stays in this zone.
    process.env.TZ = originalTz ?? "UTC";
    await postgresService.closeAll();
    await admin!.unsafe(`DROP SCHEMA IF EXISTS ${A} CASCADE; DROP SCHEMA IF EXISTS ${B} CASCADE; DROP TABLE IF EXISTS public.${PUBLIC_TABLE};`);
    await admin!.end();
  });

  it("runs in a zone where a shifted timestamp would show", () => {
    expect(new Date(2024, 0, 1).getTimezoneOffset()).toBe(-420);
  });

  it("reads the table of the schema it was asked for, not public's namesake", async () => {
    const a = await grid({ table: "users", schema: A });
    const b = await grid({ table: "users", schema: B });
    expect(a.status).toBe(200);
    expect(a.data.rows).toHaveLength(1);
    expect(b.data.rows).toEqual([[1, "b-one"]]);
    expect(b.data.sql).toContain(`FROM "${B}"."users"`);
  });

  it("defaults to public when no schema is named", async () => {
    const { data } = await grid({ table: PUBLIC_TABLE });
    expect(data.rows).toEqual([[1, "in public"]]);
  });

  it("says which columns the database numbers itself, which an integer key with no default is not", async () => {
    const res = await app().request(`/db/connections/${connId}/schema?table=numbered&schema=${A}`);
    const cols = ((await res.json()) as { data: { name: string; type: string; pk: boolean; autoIncrement: boolean }[] }).data;
    expect(cols.map((c) => [c.name, c.type, c.pk, c.autoIncrement])).toEqual([
      // SQLite's rowid alias by its type; here a key a new row has to be given.
      ["id", "integer", true, false],
      ["serial_no", "integer", false, true],
      ["always_no", "bigint", false, true],
      ["default_no", "integer", false, true],
      ["plain_no", "integer", false, false],
    ]);
    // As the database has it: an INSERT that leaves the numbered ones out is given them, and one without the key is refused.
    await admin!.unsafe(`INSERT INTO ${A}.numbered (id) VALUES (21)`);
    expect(await admin!.unsafe(`SELECT * FROM ${A}.numbered`)).toEqual([{ id: 21, serial_no: 1, always_no: "1", default_no: 1, plain_no: 7 }]);
    // postgres.js sends a query only once it is awaited, which `expect().rejects` never does.
    const refused = await admin!.unsafe(`INSERT INTO ${A}.numbered (plain_no) VALUES (1)`).then(() => "", (e: Error) => e.message);
    expect(refused).toMatch(/null value in column "id"/);
  });

  it("reads an empty schema as public on the column and export routes too, as the browser sends it", async () => {
    const cols = await app().request(`/db/connections/${connId}/schema?table=${PUBLIC_TABLE}&schema=`);
    expect(((await cols.json()) as { data: { name: string }[] }).data.map((c) => c.name)).toEqual(["id", "name"]);
    const exported = await app().request(`/db/connections/${connId}/export?table=${PUBLIC_TABLE}&schema=&format=json`);
    expect(await exported.json()).toEqual([{ id: 1, name: "in public" }]);
  });

  it("returns every value unchanged: int8 digits, numeric, dates as stored, bytes as a marker", async () => {
    const { data } = await grid({ table: "users", schema: A });
    expect(data.columns.map((c) => `${c.name}:${c.type}`)).toEqual([
      "id:bigint", "email:text", "ts:timestamp without time zone", "tstz:timestamp with time zone", "d:date",
      "n:numeric", "j:jsonb", "b:bytea", "u:uuid", "active:boolean", "tags:integer[]",
    ]);
    const [id, email, ts, tstz, d, n, j, b, u, active, tags] = data.rows[0]!;
    expect(id).toBe("9007199254740993");
    expect(email).toBe("Alice@Example.com");
    expect(ts).toBe("2024-01-01 10:00:00");
    expect(tstz).toMatch(/^2024-01-01 03:00:00\+00$/);
    expect(d).toBe("2024-01-01");
    expect(n).toBe("12345678901234567890.1234567891");
    expect(j).toEqual({ k: 1 });
    expect(b).toEqual({ $binary: "AQI=", size: 2 });
    expect(u).toBe("a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11");
    expect(active).toBe(true);
    expect(tags).toEqual([1, 2]);
  });

  it("filters text case-insensitively and non-text through a cast", async () => {
    const byEmail = await grid({ table: "users", schema: A, filters: [{ column: "email", anyOf: [[{ op: "contains", value: "alice@EXAMPLE" }]] }] });
    expect(byEmail.data.rows).toHaveLength(1);
    const byId = await grid({ table: "users", schema: A, filters: [{ column: "id", anyOf: [[{ op: "contains", value: "7409" }]] }] });
    expect(byId.data.rows).toHaveLength(1);
    expect(byId.data.sql).toContain(`CAST("id" AS TEXT) ILIKE '%7409%'`);
  });

  it("matches a big integer exactly with eq", async () => {
    const hit = await grid({ table: "users", schema: A, filters: [{ column: "id", anyOf: [[{ op: "eq", value: "9007199254740993" }]] }] });
    const miss = await grid({ table: "users", schema: A, filters: [{ column: "id", anyOf: [[{ op: "eq", value: "9007199254740992" }]] }] });
    expect(hit.data.rows).toHaveLength(1);
    expect(miss.data.rows).toHaveLength(0);
  });

  it("reads a timestamptz range in the user's zone and a timestamp range as written", async () => {
    const range = (column: string, offset: string) => grid({
      table: "users", schema: A,
      filters: [{ column, anyOf: [[{ op: "dateRange", from: "2024-01-01 10:00:00", to: "2024-01-01 10:00:01", offset }]] }],
    });
    // 03:00 UTC is 10:00 in +07:00.
    expect((await range("tstz", "+07:00")).data.rows).toHaveLength(1);
    expect((await range("tstz", "Z")).data.rows).toHaveLength(0);
    expect((await range("ts", "+07:00")).data.rows).toHaveLength(1);
  });

  it("counts exactly and reports the planner's estimate for an unfiltered table", async () => {
    const all = await post<GridCountResponse>(`/db/connections/${connId}/grid/count`, { table: "users", schema: A });
    expect(all.data).toEqual({ count: 1, estimate: 1, timedOut: false });
    const filtered = await post<GridCountResponse>(`/db/connections/${connId}/grid/count`, {
      table: "users", schema: A, filters: [{ column: "active", anyOf: [[{ op: "isFalse" }]] }],
    });
    expect(filtered.data).toEqual({ count: 0, estimate: null, timedOut: false });
  });

  it("sends a date-time parameter as the text it is, whatever this server's zone", async () => {
    const hit = await grid({ table: "users", schema: A, filters: [{ column: "ts", anyOf: [[{ op: "eq", value: "2024-01-01 10:00:00" }]] }] });
    expect(hit.data.rows).toHaveLength(1);
    const day = await grid({ table: "users", schema: A, filters: [{ column: "d", anyOf: [[{ op: "eq", value: "2024-01-01 00:00" }]] }] });
    expect(day.data.rows).toHaveLength(1);
  });

  it("saves an edited timestamp cell exactly as typed", async () => {
    await app().request(`/db/connections/${connId}/cell`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ table: "users", schema: A, pkColumn: "id", pkValue: "9007199254740993", column: "ts", value: "2024-06-01 08:30:00" }),
    });
    const [row] = await admin!.unsafe(`SELECT ts::text AS ts FROM ${A}.users`);
    expect(row!.ts).toBe("2024-06-01 08:30:00");
    await admin!.unsafe(`UPDATE ${A}.users SET ts = '2024-01-01 10:00:00'`);
  });

  it("gives up on a count that outruns its timeout, without leaving the timeout on the pool", async () => {
    const target: GridTarget = { type: "postgres", adapter: getAdapter("postgres"), config: { type: "postgres", connectionString: PG_URL! } };
    const started = Date.now();
    const result = await countGridRows(target, parseGridRequest({ table: "slow", schema: A }, "public"), 100);
    expect(result.count).toBeNull();
    expect(result.timedOut).toBe(true);
    expect(Date.now() - started).toBeLessThan(5_000);
    // A statement slower than the cancelled count's timeout still runs afterwards.
    const after = await post<QueryRunResponse>(`/db/connections/${connId}/query`, { sql: "SELECT pg_sleep(0.3) IS NULL AS slept" });
    expect(after.status).toBe(200);
  });

  it("opens a page without counting the table", async () => {
    const target: GridTarget = { type: "postgres", adapter: getAdapter("postgres"), config: { type: "postgres", connectionString: PG_URL! } };
    const started = Date.now();
    // COUNT(*) over this view would take many seconds; one page takes milliseconds.
    const page = await fetchGridPage(target, parseGridRequest({ table: "slow", schema: A, limit: 5 }, "public"));
    expect(page.response.rows).toEqual([[1], [2], [3], [4], [5]]);
    expect(page.response.hasMore).toBe(true);
    expect(Date.now() - started).toBeLessThan(3_000);
  });

  it("refuses a second statement in a grid SELECT at the driver", async () => {
    const adapter = getAdapter("postgres");
    await expect(adapter.selectRows({ type: "postgres", connectionString: PG_URL! }, { sql: "SELECT 1; SELECT 2", params: [] }))
      .rejects.toThrow(/multiple commands/i);
  });

  it("keeps repeated column names and describes an empty result", async () => {
    const dup = await post<QueryRunResponse>(`/db/connections/${connId}/query`, { sql: "SELECT 1 AS id, 2 AS id" });
    expect(dup.data.columns.map((c) => c.name)).toEqual(["id", "id"]);
    expect(dup.data.rows).toEqual([[1, 2]]);
    const empty = await post<QueryRunResponse>(`/db/connections/${connId}/query`, { sql: `SELECT * FROM ${A}.users WHERE false` });
    expect(empty.data.columns.map((c) => c.name)).toEqual(["id", "email", "ts", "tstz", "d", "n", "j", "b", "u", "active", "tags"]);
    expect(empty.data.rows).toEqual([]);
  });

  it("answers the last result of a multi-statement script and counts writes", async () => {
    const script = await post<QueryRunResponse>(`/db/connections/${connId}/query`, { sql: "SELECT 1 AS a; SELECT 2 AS b" });
    expect(script.data.columns.map((c) => c.name)).toEqual(["b"]);
    expect(script.data.rows).toEqual([[2]]);
    const write = await post<QueryRunResponse>(`/db/connections/${connId}/query`, { sql: `UPDATE ${B}.users SET name = 'renamed'` });
    expect(write.data).toMatchObject({ rowsAffected: 1, changeType: "modify" });
  });
});
