/**
 * The file icon theme: the mapping and the artwork have to stay in step.
 *
 * Both files are generated by `bun scripts/gen-file-icons.ts`, which is exactly
 * why they need a test: a name in `file-icons.generated.ts` with no class in
 * `file-icons.generated.css` renders a span of the right size with nothing in
 * it — no error, no warning, an invisible hole in a file tree. Committing one
 * of the two files without the other is the way that happens.
 */
import { describe, it, expect } from "bun:test";
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { resolve, relative } from "node:path";
import {
  DEFAULT_FILE_ICON,
  DEFAULT_FOLDER_ICON,
  DEFAULT_FOLDER_OPEN_ICON,
  EXTENSION_ICONS,
  FILENAME_ICONS,
  FOLDER_ICONS,
  FOLDER_OPEN_ICONS,
  ICON_NAMES,
} from "../../../src/web/lib/file-icons.generated.ts";
import { fileIconElement, fileIconName, folderIconName } from "../../../src/web/lib/file-icons.tsx";

const css = readFileSync(
  resolve(import.meta.dir, "../../../src/web/styles/file-icons.generated.css"),
  "utf8",
);
const classes = new Set([...css.matchAll(/^\.vsi-([a-z0-9-]+) \{/gm)].map((m) => m[1]!));

describe("the generated icon theme", () => {
  it("draws every icon the mapping can name", () => {
    const named = new Set<string>([
      DEFAULT_FILE_ICON,
      DEFAULT_FOLDER_ICON,
      DEFAULT_FOLDER_OPEN_ICON,
      ...Object.values(EXTENSION_ICONS),
      ...Object.values(FILENAME_ICONS),
      ...Object.values(FOLDER_ICONS),
      ...Object.values(FOLDER_OPEN_ICONS),
    ]);
    expect([...named].filter((n) => !classes.has(n))).toEqual([]);
  });

  it("names every icon it draws, so nothing is shipped unreachable", () => {
    expect([...classes].filter((c) => !ICON_NAMES.includes(c))).toEqual([]);
    expect(ICON_NAMES.length).toBe(classes.size);
  });

  it("gives the light-theme drawings a `:root.light` rule and no class of their own", () => {
    // A light variant is a second drawing of a glyph the app already has a class
    // for. If one ever leaked out as `.vsi-file-type-light-json`, the mapping
    // would still point at the dark class and the extra artwork would be dead
    // weight — while every light theme kept the drawing meant for a dark one.
    expect([...classes].filter((c) => c.startsWith("file-type-light-"))).toEqual([]);
    expect(css).toContain(":root.light .vsi-");
  });

  it("has no `currentColor` to inherit, which is why these are backgrounds", () => {
    expect(css).not.toContain("currentColor");
  });
});

describe("resolving a name to an icon", () => {
  it("prefers a whole filename over its extension", () => {
    expect(fileIconName("package.json")).toBe(FILENAME_ICONS["package.json"]!);
    expect(fileIconName("package.json")).not.toBe(EXTENSION_ICONS.json);
  });

  it("reads only the last path segment", () => {
    expect(fileIconName("src/web/lib/file-icons.tsx")).toBe(EXTENSION_ICONS.tsx!);
    expect(fileIconName("src\\web\\lib\\file-icons.tsx")).toBe(EXTENSION_ICONS.tsx!);
  });

  it("matches a double extension before the single one", () => {
    // `.spec.ts` and `.d.ts` have their own glyphs; falling through to `ts`
    // would lose the distinction the theme draws.
    expect(fileIconName("use-chat.test.ts")).not.toBe(EXTENSION_ICONS.ts);
    expect(fileIconName("use-chat.test.ts")).toBe(EXTENSION_ICONS["test.ts"]!);
    expect(fileIconName("shared.d.ts")).toBe(EXTENSION_ICONS["d.ts"]!);
  });

  it("is case-insensitive on both tables", () => {
    expect(fileIconName("DOCKERFILE")).toBe(fileIconName("Dockerfile"));
    expect(fileIconName("README.MD")).toBe(fileIconName("readme.md"));
  });

  it("reads a dotfile's name as its extension", () => {
    // `.npmrc` is a name with no extension by the usual reading; the theme
    // still has a glyph for it.
    expect(fileIconName(".npmrc")).toBe(EXTENSION_ICONS.npmrc!);
  });

  it("falls back to the neutral default rather than nothing", () => {
    expect(fileIconName("mystery.qqq")).toBe(DEFAULT_FILE_ICON);
    expect(fileIconName("noextension")).toBe(DEFAULT_FILE_ICON);
    expect(fileIconName("")).toBe(DEFAULT_FILE_ICON);
  });

  it("has a separate open glyph for a folder", () => {
    expect(folderIconName("src")).toBe(FOLDER_ICONS.src!);
    expect(folderIconName("src", true)).toBe(FOLDER_OPEN_ICONS.src!);
    expect(folderIconName("src")).not.toBe(folderIconName("src", true));
    expect(folderIconName("whatever")).toBe(DEFAULT_FOLDER_ICON);
    expect(folderIconName("whatever", true)).toBe(DEFAULT_FOLDER_OPEN_ICON);
  });

  it("covers what a Bun and TypeScript repository is mostly made of", () => {
    // These are the ones a size budget quietly took away once: `file-type-reactts`
    // is 1833 bytes, and a 1800-byte cap gave every `.tsx` file a blank page.
    for (const name of ["app.tsx", "app.jsx", "main.go", "lib.rs", "bun.lock", "bunfig.toml"]) {
      expect(fileIconName(name)).not.toBe(DEFAULT_FILE_ICON);
    }
  });
});

describe("a filename is not a property name", () => {
  // A file really can be called `constructor` and a directory really can be
  // called `toString`. With an ordinary object literal the lookup answers from
  // `Object.prototype` with something inherited and truthy, so the truthiness
  // check treats it as a hit: `fileIconName("constructor")` returned the
  // `Object` *function* and `fileIconName("__proto__")` returned
  // `Object.prototype`, each interpolated straight into a class name.
  const hazards = ["constructor", "toString", "valueOf", "hasOwnProperty", "__proto__", "isPrototypeOf"];

  it("gives inherited property names the default icon", () => {
    for (const name of hazards) {
      expect(fileIconName(name), `file "${name}"`).toBe(DEFAULT_FILE_ICON);
      expect(folderIconName(name), `folder "${name}"`).toBe(DEFAULT_FOLDER_ICON);
      expect(folderIconName(name, true), `open folder "${name}"`).toBe(DEFAULT_FOLDER_OPEN_ICON);
      // The extension path reaches the same tables.
      expect(fileIconName(`x.${name}`), `extension ".${name}"`).toBe(DEFAULT_FILE_ICON);
    }
  });

  it("always answers with a string, whatever the name", () => {
    // The class is built by interpolation, so a non-string answer is not an
    // error anywhere — it is `vsi-function Object() { [native code] }` in the
    // DOM and a span of nothing on screen.
    for (const name of [...hazards, "__defineGetter__", "propertyIsEnumerable"]) {
      expect(typeof fileIconName(name)).toBe("string");
      expect(typeof folderIconName(name)).toBe("string");
    }
  });

  it("keeps the tables prototype-less so this cannot come back", () => {
    for (const table of [EXTENSION_ICONS, FILENAME_ICONS, FOLDER_ICONS, FOLDER_OPEN_ICONS]) {
      expect(Object.getPrototypeOf(table)).toBeNull();
    }
  });
});

/**
 * The artwork must stay off the entry's static graph — and off the code
 * recovery path.
 *
 * One `import "@/styles/file-icons.generated.css"` anywhere the shell reaches
 * eagerly puts the whole 499 KB back into a render-blocking `<link>` in
 * `index.html`, and nothing about the app looks different when it does — which
 * is why this is enumerated rather than left to review. `file-icons.tsx` is
 * reached from `tab-type-icons.ts`, which the tab bar, the mobile nav and the
 * dock header all import at module scope.
 *
 * A *dynamic* import is no longer allowed either. Vite's preload helper
 * dispatches `vite:preloadError` when a chunk fails, `chunk-recovery.ts`
 * answers that by purging the asset caches and reloading the page, and that
 * path deliberately steps around the unsaved-work guard — which is right for a
 * missing code chunk and wrong for decorative artwork. The sheet is addressed
 * by URL and fetched by a `<link>` instead.
 */
describe("the artwork is not in the entry chunk", () => {
  const ROOT = resolve(import.meta.dir, "../../..");
  const SHEET = "styles/file-icons.generated.css";

  /**
   * Everything that can put a file into the web bundle. `src/web` alone was too
   * narrow twice over: `index.html` can carry a `<link>` of its own, and an
   * importer one directory up is just as effective.
   */
  function sources(): string[] {
    const out: string[] = [];
    const walk = (dir: string): void => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        if (entry.name === "node_modules" || entry.name === "dist") continue;
        const full = resolve(dir, entry.name);
        if (entry.isDirectory()) walk(full);
        else if (/\.(ts|tsx|css|html)$/.test(entry.name)) out.push(full);
      }
    };
    walk(resolve(ROOT, "src"));
    walk(resolve(ROOT, "packages"));
    return out;
  }

  it("is never imported as a module, statically or dynamically", () => {
    const offenders: string[] = [];
    for (const file of sources()) {
      const text = readFileSync(file, "utf8");
      // Only an import puts it on the graph — the name also appears in prose,
      // and matching the bare string flagged a doc comment. `?url` is the one
      // permitted specifier: it yields the address and fetches nothing.
      const statics = [
        ...text.matchAll(/^\s*import\s+(?:[^"';]*\s+from\s+)?["'][^"']*file-icons\.generated\.css["']/gm),
        ...text.matchAll(/@import\s+(?:url\()?["'][^"']*file-icons\.generated\.css["']/g),
        ...text.matchAll(/\brequire\(\s*["'][^"']*file-icons\.generated\.css["']/g),
        ...text.matchAll(/\bimport\(\s*["'][^"']*file-icons\.generated\.css(?:\?[^"']*)?["']/g),
        ...text.matchAll(/<link[^>]*file-icons\.generated\.css/g),
      ];
      for (const m of statics) {
        offenders.push(`${relative(ROOT, file).replaceAll("\\", "/")}: ${m[0].trim()}`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it("is still reachable — the stylesheet the `?url` import names exists", () => {
    // A typo in the specifier is a silent no-op at build time and blank icons
    // at runtime, so resolve it rather than trusting the string.
    const icons = readFileSync(resolve(ROOT, "src/web/lib/file-icons.tsx"), "utf8");
    const spec = icons.match(/from\s+"([^"]*file-icons\.generated\.css)\?url"/)?.[1];
    expect(spec, "file-icons.tsx no longer imports the artwork's URL").toBeTruthy();
    expect(existsSync(resolve(ROOT, "src/web", spec!.replace(/^@\//, "")))).toBe(true);
    expect(spec!.endsWith(SHEET)).toBe(true);
  });
});

/**
 * The fetch itself, driven rather than read.
 *
 * This suite owns `requestIconCss`'s module state — the attempt counter is not
 * resettable from outside — so it is the only place that may call something
 * which asks for an icon element, and it comes last for that reason.
 */
describe("the artwork is fetched by a link element", () => {
  interface FakeLink {
    rel: string;
    href: string;
    removed: boolean;
    fail: () => void;
  }

  function withFakeDocument<T>(links: FakeLink[], run: () => T): T {
    const previous = (globalThis as { document?: unknown }).document;
    (globalThis as { document?: unknown }).document = {
      createElement: () => {
        let onError = (): void => {};
        const link: FakeLink & { addEventListener: (t: string, f: () => void) => void; remove: () => void } = {
          rel: "",
          href: "",
          removed: false,
          addEventListener: (type: string, handler: () => void) => {
            if (type === "error") onError = handler;
          },
          remove: () => {
            link.removed = true;
          },
          fail: () => onError(),
        };
        return link;
      },
      head: { appendChild: (link: FakeLink) => links.push(link) },
    };
    try {
      return run();
    } finally {
      // Restored, because a global left behind is a failure in some other
      // suite that shares this process — and one that only appears in a batch.
      if (previous === undefined) delete (globalThis as { document?: unknown }).document;
      else (globalThis as { document?: unknown }).document = previous;
    }
  }

  it("appends one stylesheet, retries once if it fails, and never reloads the app", () => {
    const links: FakeLink[] = [];
    withFakeDocument(links, () => {
      fileIconElement("a.ts");
      expect(links).toHaveLength(1);
      expect(links[0]!.rel).toBe("stylesheet");
      expect(links[0]!.href).toContain("file-icons.generated");

      // Every icon that mounts comes through here; one sheet is enough.
      fileIconElement("b.ts");
      fileIconElement("c.ts");
      expect(links).toHaveLength(1);

      // The failure path. A dynamic import would have dispatched
      // `vite:preloadError` here, which purges the caches and reloads the page.
      links[0]!.fail();
      expect(links[0]!.removed).toBe(true);

      // One retry, so a tab that lived through a network blip can recover...
      fileIconElement("d.ts");
      expect(links).toHaveLength(2);

      // ...and then it stops, rather than one request per icon forever.
      links[1]!.fail();
      fileIconElement("e.ts");
      expect(links).toHaveLength(2);
    });
  });
});
