/**
 * The file icon theme: the mapping and the artwork have to stay in step.
 *
 * Both files are generated by `bun scripts/gen-file-icons.ts`, which is exactly
 * why they need a test: a name in `file-icons.generated.ts` with no class in
 * `file-icons.generated.css` renders a span of the right size with nothing in
 * it — no error, no warning, an invisible hole in a file tree. Committing one
 * of the two files without the other is the way that happens.
 */
import { describe, it, expect } from "bun:test";
import { readFileSync, readdirSync, existsSync } from "node:fs";
import { resolve, relative } from "node:path";
import {
  DEFAULT_FILE_ICON,
  DEFAULT_FOLDER_ICON,
  DEFAULT_FOLDER_OPEN_ICON,
  EXTENSION_ICONS,
  FILENAME_ICONS,
  FOLDER_ICONS,
  FOLDER_OPEN_ICONS,
  ICON_NAMES,
} from "../../../src/web/lib/file-icons.generated.ts";
import { fileIconName, folderIconName } from "../../../src/web/lib/file-icons.tsx";

const css = readFileSync(
  resolve(import.meta.dir, "../../../src/web/styles/file-icons.generated.css"),
  "utf8",
);
const classes = new Set([...css.matchAll(/^\.vsi-([a-z0-9-]+) \{/gm)].map((m) => m[1]!));

describe("the generated icon theme", () => {
  it("draws every icon the mapping can name", () => {
    const named = new Set<string>([
      DEFAULT_FILE_ICON,
      DEFAULT_FOLDER_ICON,
      DEFAULT_FOLDER_OPEN_ICON,
      ...Object.values(EXTENSION_ICONS),
      ...Object.values(FILENAME_ICONS),
      ...Object.values(FOLDER_ICONS),
      ...Object.values(FOLDER_OPEN_ICONS),
    ]);
    expect([...named].filter((n) => !classes.has(n))).toEqual([]);
  });

  it("names every icon it draws, so nothing is shipped unreachable", () => {
    expect([...classes].filter((c) => !ICON_NAMES.includes(c))).toEqual([]);
    expect(ICON_NAMES.length).toBe(classes.size);
  });

  it("gives the light-theme drawings a `:root.light` rule and no class of their own", () => {
    // A light variant is a second drawing of a glyph the app already has a class
    // for. If one ever leaked out as `.vsi-file-type-light-json`, the mapping
    // would still point at the dark class and the extra artwork would be dead
    // weight — while every light theme kept the drawing meant for a dark one.
    expect([...classes].filter((c) => c.startsWith("file-type-light-"))).toEqual([]);
    expect(css).toContain(":root.light .vsi-");
  });

  it("has no `currentColor` to inherit, which is why these are backgrounds", () => {
    expect(css).not.toContain("currentColor");
  });
});

describe("resolving a name to an icon", () => {
  it("prefers a whole filename over its extension", () => {
    expect(fileIconName("package.json")).toBe(FILENAME_ICONS["package.json"]!);
    expect(fileIconName("package.json")).not.toBe(EXTENSION_ICONS.json);
  });

  it("reads only the last path segment", () => {
    expect(fileIconName("src/web/lib/file-icons.tsx")).toBe(EXTENSION_ICONS.tsx!);
    expect(fileIconName("src\\web\\lib\\file-icons.tsx")).toBe(EXTENSION_ICONS.tsx!);
  });

  it("matches a double extension before the single one", () => {
    // `.spec.ts` and `.d.ts` have their own glyphs; falling through to `ts`
    // would lose the distinction the theme draws.
    expect(fileIconName("use-chat.test.ts")).not.toBe(EXTENSION_ICONS.ts);
    expect(fileIconName("use-chat.test.ts")).toBe(EXTENSION_ICONS["test.ts"]!);
    expect(fileIconName("shared.d.ts")).toBe(EXTENSION_ICONS["d.ts"]!);
  });

  it("is case-insensitive on both tables", () => {
    expect(fileIconName("DOCKERFILE")).toBe(fileIconName("Dockerfile"));
    expect(fileIconName("README.MD")).toBe(fileIconName("readme.md"));
  });

  it("reads a dotfile's name as its extension", () => {
    // `.npmrc` is a name with no extension by the usual reading; the theme
    // still has a glyph for it.
    expect(fileIconName(".npmrc")).toBe(EXTENSION_ICONS.npmrc!);
  });

  it("falls back to the neutral default rather than nothing", () => {
    expect(fileIconName("mystery.qqq")).toBe(DEFAULT_FILE_ICON);
    expect(fileIconName("noextension")).toBe(DEFAULT_FILE_ICON);
    expect(fileIconName("")).toBe(DEFAULT_FILE_ICON);
  });

  it("has a separate open glyph for a folder", () => {
    expect(folderIconName("src")).toBe(FOLDER_ICONS.src!);
    expect(folderIconName("src", true)).toBe(FOLDER_OPEN_ICONS.src!);
    expect(folderIconName("src")).not.toBe(folderIconName("src", true));
    expect(folderIconName("whatever")).toBe(DEFAULT_FOLDER_ICON);
    expect(folderIconName("whatever", true)).toBe(DEFAULT_FOLDER_OPEN_ICON);
  });

  it("covers what a Bun and TypeScript repository is mostly made of", () => {
    // These are the ones a size budget quietly took away once: `file-type-reactts`
    // is 1833 bytes, and a 1800-byte cap gave every `.tsx` file a blank page.
    for (const name of ["app.tsx", "app.jsx", "main.go", "lib.rs", "bun.lock", "bunfig.toml"]) {
      expect(fileIconName(name)).not.toBe(DEFAULT_FILE_ICON);
    }
  });
});

/**
 * The artwork must stay off the entry's static graph.
 *
 * One `import "@/styles/file-icons.generated.css"` anywhere the shell reaches
 * eagerly puts the whole 499 KB back into a render-blocking `<link>` in
 * `index.html`, and nothing about the app looks different when it does — which
 * is why this is enumerated rather than left to review. `file-icons.tsx` is
 * reached from `tab-type-icons.ts`, which the tab bar, the mobile nav and the
 * dock header all import at module scope.
 */
describe("the artwork is not in the entry chunk", () => {
  const WEB = resolve(import.meta.dir, "../../../src/web");
  const SHEET = "styles/file-icons.generated.css";

  function sources(): string[] {
    const out: string[] = [];
    const walk = (dir: string): void => {
      for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const full = resolve(dir, entry.name);
        if (entry.isDirectory()) walk(full);
        else if (/\.(ts|tsx|css)$/.test(entry.name)) out.push(full);
      }
    };
    walk(WEB);
    return out;
  }

  it("is imported dynamically, and only from the icon module", () => {
    const offenders: string[] = [];
    for (const file of sources()) {
      const text = readFileSync(file, "utf8");
      // Only an import puts it on the graph — the name also appears in prose,
      // and matching the bare string flagged a doc comment.
      const statics = [
        ...text.matchAll(/^\s*import\s+(?:[^"';]*\s+from\s+)?["'][^"']*file-icons\.generated\.css["']/gm),
        ...text.matchAll(/@import\s+(?:url\()?["'][^"']*file-icons\.generated\.css["']/g),
        ...text.matchAll(/\brequire\(\s*["'][^"']*file-icons\.generated\.css["']/g),
      ];
      for (const m of statics) {
        offenders.push(`${relative(WEB, file).replaceAll("\\", "/")}: ${m[0].trim()}`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it("is still reachable — the stylesheet the dynamic import names exists", () => {
    // A typo in the specifier is a silent no-op at build time and blank icons
    // at runtime, so resolve it rather than trusting the string.
    const icons = readFileSync(resolve(WEB, "lib/file-icons.tsx"), "utf8");
    const spec = icons.match(/import\("([^"]*file-icons\.generated\.css)"\)/)?.[1];
    expect(spec, "file-icons.tsx no longer dynamically imports the artwork").toBeTruthy();
    expect(existsSync(resolve(WEB, spec!.replace(/^@\//, "")))).toBe(true);
    expect(spec!.endsWith(SHEET)).toBe(true);
  });
});
