/**
 * Vendor the icons the Git Graph webview draws into one module.
 *
 * The panel is a sandboxed iframe, so it cannot use `@/lib/icons` — it gets
 * the same glyphs as SVG strings instead: Fluent System Icons at **20px
 * Regular**, the set the app's own chrome is drawn in (`gen-product-icons.ts`),
 * so a button in the graph and the same button in Source Control look alike.
 * The two glyphs the app keeps from lucide (`GitCommitHorizontal`, `FileDiff`)
 * are kept here too, for the same reason it keeps them: Fluent has neither.
 *
 * Keys are the names the webview script asks for (`ic('push')`); the values
 * are whole `<svg class="ic">` elements, sized by the panel's CSS.
 *
 *   bun scripts/gen-git-graph-icons.ts
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const OUT = resolve(import.meta.dir, "../packages/ext-git-graph/src/webview-icons.generated.ts");

/** Webview name → Fluent name, without the `-20-regular` suffix. */
const MAP: Record<string, string> = {
  "chev-d": "chevron-down",
  "chev-r": "chevron-right",
  "chev-l": "chevron-left",
  "chev-u": "chevron-up",
  "arrow-up": "arrow-up",
  "arrow-down": "arrow-down",
  push: "arrow-upload",
  pull: "arrow-download",
  sync: "arrow-sync",
  more: "more-horizontal",
  "more-v": "more-vertical",
  external: "open",
  x: "dismiss",
  check: "checkmark",
  "check-circle": "checkmark-circle",
  plus: "add",
  minus: "subtract",
  trash: "delete",
  copy: "copy",
  search: "search",
  filter: "filter",
  revert: "arrow-counterclockwise",
  undo: "arrow-undo",
  reset: "arrow-reset",
  warn: "warning",
  alert: "error-circle",
  info: "info",
  history: "history",
  doc: "document-text",
  folder: "folder",
  "folder-open": "folder-open",
  tree: "text-bullet-list-tree",
  list: "text-bullet-list-ltr",
  tag: "tag",
  "panel-right": "panel-right",
  columns: "layout-column-three",
  terminal: "window-console",
  branch: "branch",
  settings: "settings",
  options: "options",
  cloud: "cloud",
  "cloud-off": "cloud-off",
  people: "people",
  edit: "edit",
  spinner: "spinner-ios",
  stash: "archive",
  merge: "merge",
  fork: "branch-fork",
  compare: "branch-compare",
  cherry: "copy-arrow-right",
  checkout: "arrow-enter",
  swap: "arrow-swap",
  cube: "cube",
  pr: "branch-request",
  rebase: "arrow-routing",
  "list-checks": "task-list-square-ltr",
  link: "link",
  eye: "eye",
  "eye-off": "eye-off",
};

/** lucide (ISC), 24px stroked: the glyphs Fluent does not have. */
const LUCIDE: Record<string, string> = {
  commit: '<circle cx="12" cy="12" r="3"/><line x1="3" x2="9" y1="12" y2="12"/><line x1="15" x2="21" y1="12" y2="12"/>',
  "file-diff":
    '<path d="M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z"/><path d="M9 10h6"/><path d="M12 13V7"/><path d="M9 17h6"/>',
};

const collection = (
  await import("@iconify-json/fluent/icons.json", { with: { type: "json" } })
).default as { icons: Record<string, { body: string }>; width?: number; height?: number };
const version = (
  await import("@iconify-json/fluent/info.json", { with: { type: "json" } })
).default.version as string;

const svgs: Record<string, string> = {};
const missing: string[] = [];
for (const [name, fluent] of Object.entries(MAP)) {
  const icon = collection.icons[`${fluent}-20-regular`];
  if (!icon) {
    missing.push(`${name} → ${fluent}`);
    continue;
  }
  // A body that is not plain paths (a <g>, a fill-rule) would still render;
  // it is copied whole rather than re-built from its `d` attributes.
  svgs[name] = `<svg class="ic" viewBox="0 0 ${collection.width ?? 20} ${collection.height ?? 20}" aria-hidden="true">${icon.body}</svg>`;
}
for (const [name, body] of Object.entries(LUCIDE)) {
  svgs[name] =
    `<svg class="ic" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${body}</svg>`;
}
if (missing.length) {
  console.error(`Not in @iconify-json/fluent:\n  ${missing.join("\n  ")}`);
  process.exit(1);
}
for (const [name, svg] of Object.entries(svgs)) {
  // The table is spliced into the webview's script and HTML.
  if (/[`]|<\/script|<!--/i.test(svg)) throw new Error(`${name}: cannot be inlined`);
}

const names = Object.keys(svgs).sort();
const out = `/**
 * Generated by scripts/gen-git-graph-icons.ts — do not edit.
 *
 * Fluent System Icons 20px Regular (MIT, microsoft/fluentui-system-icons ${version}),
 * plus lucide's ${Object.keys(LUCIDE).map((n) => `\`${n}\``).join(" and ")} (ISC), as SVG strings for the Git Graph webview.
 */
export const WEBVIEW_ICONS: Record<string, string> = {
${names.map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(svgs[n])},`).join("\n")}
};
`;
writeFileSync(OUT, out);
console.log(`${names.length} icons → ${OUT} (${(out.length / 1024).toFixed(1)} KiB)`);
