/**
 * Turns the emulator's `emulator_controller.proto` into a JSON descriptor the bundler can embed.
 *
 * `@grpc/proto-loader`'s `loadSync()` reads the .proto off disk at call time, and in a compiled
 * PPM that path resolves under `file:///$bunfs/root/` where no such file exists — measured, it
 * throws ENOENT at `loadProtosWithOptionsSync`. Same family as the `bundledServerEntry` trap in
 * CLAUDE.md. So the descriptor is generated here and `import`ed as a module instead.
 *
 * Re-run after changing the .proto:  bun scripts/gen-android-proto.ts
 */
import protobuf from "protobufjs";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const DIR = resolve(import.meta.dir, "..", "src", "services", "android", "proto");
const SRC = resolve(DIR, "emulator_controller.proto");
const OUT = resolve(DIR, "emulator-controller-descriptor.ts");

const root = await protobuf.load(SRC);
const sha = createHash("sha256").update(readFileSync(SRC)).digest("hex");

writeFileSync(OUT, `// GENERATED by scripts/gen-android-proto.ts — do not edit.
//
// Source:   emulator_controller.proto (Apache 2.0, The Android Open Source Project)
// Taken from: $ANDROID_SDK_ROOT/emulator/lib/emulator_controller.proto
// Emulator: 36.5.10.0 (build 15081367)
// SHA-256:  ${sha}
//
// Embedded rather than loaded from disk: a compiled binary cannot read the .proto file.
export const EMULATOR_CONTROLLER_PROTO_SHA256 = ${JSON.stringify(sha)};
export const emulatorControllerDescriptor = ${JSON.stringify(root.toJSON({ keepComments: false }))} as const;
`);

console.log(`wrote ${OUT}`);
console.log(`  sha256 ${sha}`);
console.log(`  ${(readFileSync(OUT).length / 1024).toFixed(0)} KiB`);
